FROM rust:1.63 as build

WORKDIR /app
ADD ./ /app

LABEL MAINTAINER="roman <contact@romnn.com>"

RUN cargo build --release --features "builtin" --all-targets

FROM gcr.io/distroless/cc
COPY --from=build /app/target/release/film-borders /
CMD ["./film-borders"]
