name: build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Pack wasm
      run: |
        pip install invoke
        npm install --global yarn
        cargo install wasm-pack
        invoke pack
    - name: Build page
      run: |
        cd www
        yarn install
        yarn build
