name: build

on: [push, pull_request]

jobs:
  feature-matrix:
    uses: ./.github/workflows/feature-matrix.yml

  build:
    name: build (features ${{ matrix.features }})
    runs-on: ubuntu-latest
    needs: [feature-matrix]
    strategy:
      fail-fast: false
      matrix:
        features: ${{ fromJson(needs.feature-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Compile binaries
        run: >-
          cargo build
          --profile lib
          --features "${{ matrix.features }}"
          --all-targets

  pack-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/setup-python@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Pack wasm
        run: |
          pip install pipenv
          pipenv install --dev
          npm install --global yarn
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          pipenv run invoke pack
      - name: Build page
        run: |
          cd www
          yarn install
          yarn build
