name: release

on:
  push:
    tags:
      - '*'

jobs:
  publish-docker-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - id: query
        uses: romnnn/query-git-action@master
      
      - name: Login to registry.romnn.com
        uses: docker/login-action@v1
        with:
          registry: core.registry.romnn.com
          username: ${{ secrets.CONTAINER_REG_USERNAME }}
          password: ${{ secrets.CONTAINER_REG_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            version=${{ steps.query.outputs.stable_semver_version }}
          tags: |
            core.registry.romnn.com/romnn/hipster:latest
            core.registry.romnn.com/romnn/hipster:${{ steps.query.outputs.stable_docker_tag }}
