name: test

on: [push, pull_request]

jobs:
  feature-matrix:
    uses: ./.github/workflows/feature-matrix.yml

  test:
    runs-on: ubuntu-latest
    name: test (features ${{ matrix.features }})
    strategy:
      fail-fast: false
      matrix:
        features: ${{ fromJson(needs.feature-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Test
        run: >-
          cargo test
          --profile lib
          --features "${{ matrix.features }}"
          --all-targets
